### ISSUE TITLE
[Feature Request] tracks glow portal color instead of purple

### ISSUE THREAD

**Issue by steve-the-player** [misigno/createdpcompat-1.20.X#4]
when a train track connects to a Datapack portal, it glows purple. This looks fine when connecting to a nether portal, but it looks really strange when the portal color is something different. I don't know if it would be possible to change this, but it would be nice

**Comment by misigno** [comment]
The track glow comes from a custom texture when connecting to a portal. Thus i can't change it dynamically. aether portals were made compatible with create in latest version but it still glows purple when connected to the portal. I have tried to make it dynamic by applying a translucent layer over the track but making the track use this kind of rendering breaks the model at certain angles. What i can do is change the texture of the portal track to be neutral and change the color of the particles based on the color of the portal.
![2024-03-28_10 53 15](https://github.com/misigno/createdpcompat-1.20.X/assets/5872835/fcc8a4ee-c1d6-48ec-a048-40b8481848b5)
Notice the broken texture at the back of the track.
![2024-03-28_10 57 02](https://github.com/misigno/createdpcompat-1.20.X/assets/5872835/5bd2d4ad-4419-4787-92e9-3e1bb8a1555f)
Making the track texture neutral and adding colored particles.
But the texture change can be overwritten with any ressourcepack and since this is more a dirty patch rather than a proper feature i won't implement it until create changes the way the portal track texture is rendered.

**Comment by steve-the-player** [comment]
yeah, I had a feeling it would be the case. Thanks for confirming
